/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buoi7_luyentap1;

import buoi7_luyentap1.model.Hocsinh;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Buoi7 extends javax.swing.JFrame {

    ArrayList<Hocsinh> lisHocsinh = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    int index;

    public Buoi7() {
        initComponents();
        setLocationRelativeTo(null);
        lisHocsinh.add(new Hocsinh("le thi hai", "anh", 20));
        lisHocsinh.add(new Hocsinh("le thi thuy", "phap", 26));
        lisHocsinh.add(new Hocsinh("le thi tho", "nga", 21));
        lisHocsinh.add(new Hocsinh("le thi huynh", "lao", 23));
        model = (DefaultTableModel) tblTable.getModel();
        fillToTable();
        if (lisHocsinh.size() > 0) {
            index = 0;
            showDetail();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHoten = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtTuoi = new javax.swing.JTextField();
        lblTuoi = new javax.swing.JLabel();
        lblNgoaiNgu = new javax.swing.JLabel();
        cboNgoaingu = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrew = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHoten.setText("Họ tên");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnOpen.setText("Open");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblTuoi.setText("Tuổi");

        lblNgoaiNgu.setText("Ngoại ngữ");

        cboNgoaingu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "anh", "pháp", "canada", "Trung" }));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrew.setText("<<");
        btnPrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrewActionPerformed(evt);
            }
        });

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Họ tên", "Tuổi", "Ngoại ngữ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblHoten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(lblNgoaiNgu, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnPrew, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(84, 84, 84)
                                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(44, 44, 44))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtHoTen)
                                                .addComponent(txtTuoi, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnDelete)
                                                .addComponent(btnUpdate)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnClear)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnOpen))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnAdd)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnSave)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cboNgoaingu, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHoten)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClear)
                        .addComponent(btnOpen))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTuoi)
                                .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAdd)
                                .addComponent(btnSave))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNgoaiNgu)
                                .addComponent(cboNgoaingu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnDelete)
                            .addGap(12, 12, 12)
                            .addComponent(btnUpdate)))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrew)
                        .addComponent(btnFirst)
                        .addComponent(btnNext)
                        .addComponent(btnLast))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed

    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("a.txt"));
            oos.writeObject(lisHocsinh);
            oos.flush();
            oos.flush();
            oos.close();
            oos.close();
            JOptionPane.showMessageDialog(this, "Save thanh cong");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi save ");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (txtHoTen.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "ho ten khong duoc rong");
                txtHoTen.requestFocus();
                return;
            }
            if (txtTuoi.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "tuoi khong duoc rong");
                txtTuoi.requestFocus();
                return;
            }
            int tuoi;
            try {
                tuoi = Integer.parseInt(txtTuoi.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "tuoi phai la so");
                txtTuoi.requestFocus();
                return;
            }
            if (tuoi < 15 || tuoi > 65) {
                JOptionPane.showMessageDialog(this, "tuoi phai 15-65");
                txtTuoi.requestFocus();
                return;
            }
            String name = txtHoTen.getText();
            String ngoaiNgu = (String) cboNgoaingu.getSelectedItem();
            Hocsinh hs = new Hocsinh(name, ngoaiNgu, tuoi);
            lisHocsinh.add(hs);
            model.addRow(new Object[]{hs.getHoten(), hs.getTuoi(), hs.getNgoaiNgu(), hs.getStatus(tuoi)});
            if (lisHocsinh.size() > 0) {
                index = 0;
                showDetail();
            } else {
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi add");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            if (lisHocsinh.size() == 0) {
                JOptionPane.showMessageDialog(this, "Không có dữ liệu để xóa");
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            lisHocsinh.remove(index);
            model.removeRow(index);
            //
            if (lisHocsinh.size() > 0) {
                index = 0;
                showDetail();
            } else {
                clearForm();
            }
            JOptionPane.showMessageDialog(this, "Xóa dữ liệu thành công");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nốt delete");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (txtHoTen.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "ho ten khong duoc rong");
                txtHoTen.requestFocus();
                return;
            }
            if (txtTuoi.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "tuoi khong duoc rong");
                txtTuoi.requestFocus();
                return;
            }
            int tuoi;
            try {
                tuoi = Integer.parseInt(txtTuoi.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "tuoi phai la so");
                txtTuoi.requestFocus();
                return;
            }
            if (tuoi < 15 || tuoi > 65) {
                JOptionPane.showMessageDialog(this, "tuoi phai 15-65");
                txtTuoi.requestFocus();
                return;
            }
            String name = txtHoTen.getText();
            String ngoaiNgu = (String) cboNgoaingu.getSelectedItem();
            Hocsinh hs = new Hocsinh(name, ngoaiNgu, tuoi);
            index = tblTable.getSelectedRow();
            lisHocsinh.set(index, hs);
            model.setValueAt(name, index, 0);
            model.setValueAt(tuoi, index, 1);
            model.setValueAt(ngoaiNgu, index, 2);
            

            if (lisHocsinh.size() > 0) {
                index = 0;
                showDetail();
            } else {
                clearForm();
            }
            JOptionPane.showMessageDialog(this, "Update thanh cong");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Loi update");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try {
            index = 0;
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "khong the tien nua");
            return;
        }
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrewActionPerformed
        try {
            if (index > 0) {
                index--;
            }
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "loi lui");
            return;
        }
    }//GEN-LAST:event_btnPrewActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            if (index < lisHocsinh.size() - 1) {
                index++;
            }
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "khong the tien nua");
            return;
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            index = lisHocsinh.size() - 1;
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "khong the lui nua");
            return;
        }
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTableMouseClicked
        index = tblTable.getSelectedRow();
        showDetail();
    }//GEN-LAST:event_tblTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buoi7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buoi7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buoi7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buoi7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buoi7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPrew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboNgoaingu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHoten;
    private javax.swing.JLabel lblNgoaiNgu;
    private javax.swing.JLabel lblTuoi;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables

    private void fillToTable() {
        model.setRowCount(0);
        for (Hocsinh hs : lisHocsinh) {
            model.addRow(new Object[]{hs.getHoten(), hs.getTuoi(), hs.getNgoaiNgu(), hs.getStatus(hs.getTuoi())});
        }
    }

    private void showDetail() {
        Hocsinh hs = lisHocsinh.get(index);
        txtHoTen.setText(hs.getHoten());
        txtTuoi.setText(hs.getTuoi() + "");
        cboNgoaingu.setSelectedItem(hs.getNgoaiNgu());
        tblTable.setRowSelectionInterval(index, index);

    }

    private void clearForm() {
        txtHoTen.setText("");
        txtTuoi.setText("");
        cboNgoaingu.setSelectedItem("");
        index = -1;
    }
}
